import { getUsersUseCase } from "../../application/use-cases/admin/getUsersUseCase";
import { userManageController } from "../controllers/admin/userManageController";
import { authRepository } from "../../infrastructure/db/repositories/auth/authRepository";
import { getCompanysUseCase } from "../../application/use-cases/admin/getCompanysUseCase";
import { BaseRepository } from "../../infrastructure/db/base/BaseRepository";
import { Company } from "../../infrastructure/db/models/company/companySchema";
import { companyManageController } from "../controllers/admin/companyManageController";
import { companyApproveRejectUsecase } from "../../application/use-cases/admin/companyApproveRejectUsecase";
import { User } from "../../infrastructure/db/models/user/userSchema";
import { blockUserUseCase } from "../../application/use-cases/admin/blockUserUseCase";
import { EmailService } from "../../application/services/emailService";
import { LessonManageController } from "../controllers/admin/lessonManageController";
import { createLessonUseCase } from "../../application/use-cases/admin/lessonManagementUseCases/createLessonUseCase";
import { Lesson } from "../../infrastructure/db/models/admin/lessonSchema";
import { getLessonUseCase } from "../../application/use-cases/admin/lessonManagementUseCases/getLessonUseCase";
import { updateLessonUseCase } from "../../application/use-cases/admin/lessonManagementUseCases/updateLessonUseCase";
import { deleteLessonUseCase } from "../../application/use-cases/admin/lessonManagementUseCases/deleteLessonUseCase";
const authRepo = new authRepository();
const baseRepoUser=new BaseRepository(User);
const BlockUserUseCase = new blockUserUseCase(baseRepoUser);
const baseRepoCompany=new BaseRepository(Company);
const GetUsers = new getUsersUseCase(authRepo);
const getCompanyUseCase=new getCompanysUseCase(baseRepoCompany);
const emailService=new EmailService();
const CompanyApproveRejectUseCase=new companyApproveRejectUsecase(baseRepoCompany,baseRepoUser,emailService);
const baseRepoLesson=new BaseRepository(Lesson);
const lessonCreateUseCase=new createLessonUseCase(baseRepoLesson);
const GetLessonUseCase=new getLessonUseCase(baseRepoLesson);
const UpdateLessonUseCase=new updateLessonUseCase(baseRepoLesson);
const DeleteLessonUseCase=new deleteLessonUseCase(baseRepoLesson);
export const injectCompanyManageController=new companyManageController(getCompanyUseCase,CompanyApproveRejectUseCase);
export const injectUserManageController = new userManageController(GetUsers,BlockUserUseCase);
export const injectLessonManageController=new LessonManageController(lessonCreateUseCase,GetLessonUseCase,UpdateLessonUseCase,DeleteLessonUseCase);