import { MyLessonsController } from "../controllers/company-user/MyLessonsController";
import { BaseRepository } from "../../infrastructure/db/base/BaseRepository";
import { LessonAssignment } from "../../infrastructure/db/models/company/lesssonAssigmentSchema";
import { getMyLessonsUseCase } from "../../application/use-cases/companyUser/getMyLessonsUseCase";
import { User } from "../../infrastructure/db/models/user/userSchema";
import { Lesson } from "../../infrastructure/db/models/admin/lessonSchema";
import { getAssignLessonUseCase } from "../../application/use-cases/companyUser/getAssignLessonUseCase";
import { saveLessonResultUseCase } from "../../application/use-cases/companyAdmin/companyLessonUseCases/saveLessonResultUseCase";
import { LessonResult } from "../../infrastructure/db/models/company/LessonResultSchema";
import { ContestsController } from "../controllers/company-user/ContestsController";
import { getOpenContestsUseCase } from "../../application/use-cases/companyUser/getOpenContestsUseCase";
import { Contest } from "../../infrastructure/db/models/company/companyContestSchema";
import { joinOrLeaveContestUseCase } from "../../application/use-cases/companyUser/joinOrLeaveContestUseCase";
import { getGroupConstestsUsecase } from "../../application/use-cases/companyUser/getGroupContestsUseCase";
import { companyGroupRepositroy } from "../../infrastructure/db/repositories/companyUser/companyGroupRepository";
import { CompanyGroup } from "../../infrastructure/db/models/company/companyGroupSchema";
import { contestRepository } from "../../infrastructure/db/repositories/companyUser/contestRepository";
import { getContestUseCase } from "../../application/use-cases/companyUser/getContestUseCase";
import { getContestDataUseCase } from "../../application/use-cases/companyUser/getContestDataUseCase";
const BaseAssignmentLessonRepository=new BaseRepository(LessonAssignment);
const BaseRepoUser=new BaseRepository(User);
const BaseRepoLesson=new BaseRepository(Lesson);
const BaseRepoLessonResult=new BaseRepository(LessonResult);
const GetAssignLessonUseCase=new getAssignLessonUseCase(BaseAssignmentLessonRepository);
const GetMyLessonsUseCase=new getMyLessonsUseCase(BaseAssignmentLessonRepository,BaseRepoUser,BaseRepoLesson);
const SaveLessonResultUseCase=new saveLessonResultUseCase(BaseRepoLessonResult,BaseAssignmentLessonRepository);
const baseRepoContest=new BaseRepository(Contest);
const GetOpenContestsUseCase=new getOpenContestsUseCase(baseRepoContest,BaseRepoUser);
const JoinOrLeaveContestUseCase=new joinOrLeaveContestUseCase(baseRepoContest,BaseRepoUser);
const CompanyGroupRepository=new companyGroupRepositroy(CompanyGroup);
const ContestRepository=new contestRepository(Contest);
const GetGroupContestsUseCase=new getGroupConstestsUsecase(baseRepoContest,BaseRepoUser,CompanyGroupRepository,ContestRepository);
const GetContestUseCase=new getContestUseCase(baseRepoContest,BaseRepoUser,ContestRepository);
const GetContestDataUseCase=new getContestDataUseCase(baseRepoContest,BaseRepoUser,ContestRepository);
export const injectContestController=new ContestsController(GetOpenContestsUseCase,JoinOrLeaveContestUseCase,GetGroupContestsUseCase,GetContestUseCase,GetContestDataUseCase);
export const injectMyLessonsController= new MyLessonsController(GetMyLessonsUseCase,GetAssignLessonUseCase,SaveLessonResultUseCase); 