import { GroupSocketController } from "../../infrastructure/socket/groupSocketController";
import { RemoveMemberGroupPlayGroupUseCase } from "../../application/use-cases/user/group-play/RemoveMemberGroupPlayGroupUseCase";
import { BaseRepository } from "../../infrastructure/db/base/BaseRepository";
import { Group } from "../../infrastructure/db/models/user/groupSchema";
import { User } from "../../infrastructure/db/models/user/userSchema";
import { ValidateGroupPlayMemberUseCase } from "../../application/use-cases/user/group-play/ValidateGroupPlayMemberUseCase";
import { Competition } from "../../infrastructure/db/models/user/competitionSchema";
import { finishGroupPlayUseCase } from "../../application/use-cases/user/group-play/finishGroupPlayUseCase";
import { Result } from "../../infrastructure/db/models/user/resultSchema";
import { quickSocketController } from "../../infrastructure/socket/quickSocketController";
import { getJoinMemberUseCase } from "../../application/use-cases/user/quick-play/getJoinMemberUseCase";
import { finishQuickPlayResultUseCase } from "../../application/use-cases/user/quick-play/finishQuickPlayUseCase";
const baseRepoCompetion=new BaseRepository(Competition);
const baseRepoGroup=new BaseRepository(Group);
const baseRepoUser=new BaseRepository(User);
const baseRepoResult=new BaseRepository(Result);
const removeMemberUseCase=new RemoveMemberGroupPlayGroupUseCase(baseRepoGroup,baseRepoUser);
const validateGroupPlayMemberUseCase=new ValidateGroupPlayMemberUseCase(baseRepoGroup,baseRepoCompetion);
const FinishGroupPlayUseCase=new finishGroupPlayUseCase(baseRepoCompetion,baseRepoGroup,baseRepoResult);
const getJoinMemberUseCaseInstance=new getJoinMemberUseCase(baseRepoCompetion,baseRepoUser);
const FinishQuickPlayResultUseCase=new finishQuickPlayResultUseCase(baseRepoCompetion,baseRepoResult)
export const injectQuickSocketController=new quickSocketController(getJoinMemberUseCaseInstance,FinishQuickPlayResultUseCase);
export const injectGroupSocketController =new GroupSocketController(removeMemberUseCase,validateGroupPlayMemberUseCase,FinishGroupPlayUseCase);