import { companyRequestController } from "../controllers/user/companyRequestController";
import { companyRequestUseCase } from "../../application/use-cases/user/companyRequestUseCase";
import { BaseRepository } from "../../infrastructure/db/base/BaseRepository";
import { Company } from "../../infrastructure/db/models/company/companySchema";
import { userController } from "../controllers/user/userController";
import { TokenService } from "../../application/services/tokenService";
import { findUserUseCase } from "../../application/use-cases/user/findUserUseCase";
import { User } from "../../infrastructure/db/models/userSchema";
import { AuthUserEntity } from "../../domain/entities";
import { updateUserUseCase } from "../../application/use-cases/user/updateUserUseCase";
import { getCompanyUseCase } from "../../application/use-cases/user/getCompanyUseCase";
import { companyReApplyUseCase } from "../../application/use-cases/user/companyReApplyUseCase";
const baseRepoCompany=new BaseRepository(Company);
const baseRepoUser=new BaseRepository<AuthUserEntity>(User);
const CompanyRequestUseCase=new companyRequestUseCase(baseRepoCompany,baseRepoUser);
const tokenService=new TokenService();
const FindUserUseCase=new findUserUseCase(baseRepoUser);
const GetCompanyUseCase=new getCompanyUseCase(baseRepoCompany);
const CompanyReApplyUseCase=new companyReApplyUseCase(baseRepoCompany,baseRepoUser)
export const injectCompanyRequestController=new companyRequestController(CompanyRequestUseCase,tokenService,FindUserUseCase,GetCompanyUseCase,CompanyReApplyUseCase);
const UpdateUserUseCase=new updateUserUseCase(baseRepoUser);
export const injectUserController =new userController(tokenService,FindUserUseCase,UpdateUserUseCase);