name: Frontend Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create env file
        run: |
          echo "VITE_API_URL=https://api.typegrid.in" >> .env
          echo "VITE_GOOGLE_CLIENT_ID=538999956200-0ar7t7ashcaigbalun7ovhkvvuhe3q5v.apps.googleusercontent.com" >> .env
          echo "VITE_TEST=fahad" >> .env
          echo "VITE_STRIPE_PUBLISHABLE_KEY=pk_test_51TM3qRLw5iKPWFW5jqXtg1R4twn7d7q2qkrUK7gwxqiYsoUtrueHfXrCTzFpLh84b8jJkcLeFTkWNzT15oipnJEV00gzTYBRhMpm2" >> .env

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-south-1

      - name: Upload to S3
        run: aws s3 sync dist/ s3://typegrid-frontend --delete

      - name: Clear CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id E2JNPCWZJHS8JJ --paths "/*"